<div class="form-group">
    <label for="exampleInputEmail1">Especialidad</label>
    <label class="form-control">
        <?php echo $this->datos[0]['espNombre']; ?>
    </label>
</div>
<div class="form-group" id="CargarMedico">
    <label for="exampleInputEmail1">Medico</label>
    <label class="form-control">
        <?php echo ucwords(strtolower($this->datos[0]['docNombre'] . ' ' . $this->datos[0]['docApellido'])); ?>
    </label>
</div>
<div class="form-group">
    <label for="exampleInputEmail1">Sede</label>
    <label class="form-control">
        <?php echo $this->datos[0]['sedeNombre'] . ' ' . $this->datos[0]['sedeDireccion']; ?>
    </label>
</div>
<div class="form-group">
    <label for="exampleInputEmail1">Fecha Cita</label>
    <label class="form-control">
        <?php echo $this->datos[0]['pdoFecha']; ?>
    </label>
</div>
<div class="form-group">
    <label for="exampleInputEmail1">Hora Cita</label>
    <label class="form-control">
        <?php echo $this->datos[0]['pdoHora']; ?>
    </label>
</div>

